/**
 * lib/feeds/embedFeedLoader.ts
 *
 * Server-side utility to read the baked embed feed that the GitHub Actions
 * workflow (update-embed-feed.yml) writes to public/feeds/embed-feed.json.
 *
 * Usage in a Next.js Server Component or API route:
 *
 *   import { loadEmbedFeed } from '@/lib/feeds/embedFeedLoader';
 *   const feed = await loadEmbedFeed();
 *
 * Architecture justification: render-on-demand / static bake pattern —
 * docs/ARCHITECTURE.md §10. Heavy API work happens in CI; the runtime reads
 * a pre-built JSON file, keeping production latency near zero.
 *
 * Security: this file is server-only. No secrets are read here — the JSON
 * file contains only public embed codes generated by the CI script.
 */

import 'server-only';

import { readFileSync } from 'node:fs';
import { join } from 'node:path';

// ── Types ─────────────────────────────────────────────────────────────────────

/** A single baked embed item produced by scripts/update-embed-feed.mjs. */
export interface EmbedFeedItem {
  /** Stable external ID (YouTube videoId, Instagram media id, …). */
  id: string;
  /** Provider name — 'youtube' | 'instagram'. */
  provider: string;
  /** Post / video title or caption (first 120 chars for Instagram). */
  title: string;
  /** Direct link to the original post. */
  permalink: string;
  /** ISO timestamp of publication. */
  published_at: string;
  /** Platform view / play count. 0 when unavailable (e.g. Instagram). */
  view_count: number;
  /** Normalised lower-case tags / hashtags. */
  tags: string[];
  /** Ready-to-use iframe / blockquote embed code. */
  embed_html: string;
  /** Preview thumbnail URL (may be empty string). */
  thumbnail_url: string;
  /** Channel / account name. */
  channel_title: string;
}

/** Algorithm settings that were active when the feed was generated. */
export interface EmbedFeedAlgorithm {
  min_view_count: number;
  required_tags: string[];
  max_items: number;
  sources: string[];
}

/** Full shape of public/feeds/embed-feed.json. */
export interface EmbedFeed {
  /** ISO timestamp of when the feed was last baked by the workflow. */
  generated_at: string;
  /** Algorithm settings used during the last bake. */
  algorithm: EmbedFeedAlgorithm;
  /** Ordered list of embed items (newest first). */
  items: EmbedFeedItem[];
}

// ── Loader ────────────────────────────────────────────────────────────────────

const FEED_PATH = join(process.cwd(), 'public', 'feeds', 'embed-feed.json');

/** Empty feed returned when the file is missing or malformed. */
const EMPTY_FEED: EmbedFeed = {
  generated_at: '',
  algorithm: {
    min_view_count: 0,
    required_tags: [],
    max_items: 0,
    sources: [],
  },
  items: [],
};

/**
 * Reads and returns the baked embed feed from disk.
 *
 * Returns an empty feed (not an error) if the file has not yet been generated
 * by the workflow, so callers can handle the "no items yet" state gracefully.
 */
export function loadEmbedFeed(): EmbedFeed {
  try {
    const raw = readFileSync(FEED_PATH, 'utf-8');
    const parsed = JSON.parse(raw) as EmbedFeed;
    if (!Array.isArray(parsed.items)) {
      return EMPTY_FEED;
    }
    return parsed;
  } catch {
    return EMPTY_FEED;
  }
}

/**
 * Convenience helper — returns only items from a specific provider.
 *
 * @example
 *   const ytItems = loadEmbedFeedByProvider('youtube');
 */
export function loadEmbedFeedByProvider(provider: string): EmbedFeedItem[] {
  return loadEmbedFeed().items.filter((item) => item.provider === provider);
}