import { ContentAsset, ContentAssetCategory, CONTENTENGIN_VERSION } from '../assetTypes'; import { resetPartIds } from '../builders/primitiveBuilder'; import { assignProceduralUv } from '../builders/uvGenerator'; import { assignProceduralTextureNames, } from '../builders/textureBuilder'; import { defaultMaterials } from '../materials/proceduralMaterials'; import { SHADERS } from '../shaders/shaderRegistry'; import { resolveRecipe } from '../recipes/recipeResolver'; import { buildHumanoidParts } from '../grammars/humanoidGrammar'; import { buildAnimalParts } from '../grammars/animalGrammar'; import { buildVehicleParts } from '../grammars/vehicleGrammar'; import { buildBicycleParts } from '../grammars/bicycleGrammar'; import { buildBuildingParts } from '../grammars/buildingGrammar'; import { buildRoadParts } from '../grammars/roadGrammar'; import { buildBridgeParts } from '../grammars/bridgeGrammar'; import { buildTerrainParts } from '../grammars/terrainGrammar'; import { buildTreeParts } from '../grammars/treeGrammar'; import { buildWaterParts } from '../grammars/waterGrammar'; import { buildPropParts } from '../grammars/propGrammar'; import { generateCollision } from './generateCollision'; import { generateLods } from './generateLods'; import { validateAsset } from './validate'; import { safeSegment } from './paths'; import { createSkeleton } from '../rigging/fitArmature'; import { createContentEnginRuntimeProfile } from '../runtimeProfile'; import { createContentEnginPerformancePlan } from '../performancePlan';
function categoryFor(t:string):ContentAssetCategory{ if(t==='humanoid')return'humanoid'; if(['quadruped','animal','bird','fish'].includes(t))return'animal'; if(t==='creature')return'creature'; if(['car','truck','vehicle','bicycle','motorcycle'].includes(t))return'vehicle'; if(['building'].includes(t))return'architecture'; if(['road','bridge'].includes(t))return'civil'; if(['terrain','tree','water'].includes(t))return'environment'; return'prop'; }
function applyProceduralPartHints(parts: ReturnType<typeof partsFor>, recipe: ReturnType<typeof resolveRecipe>) {
  const hints = Array.isArray(recipe.parameters.proceduralPartHints) ? recipe.parameters.proceduralPartHints as Array<{ label?: string; fit?: unknown; regionId?: string }> : [];
  if (!hints.length) return parts;
  const byLabel = new Map(hints.map((hint) => [hint.label, hint]));
  const attach = (part: typeof parts[number]): typeof parts[number] => {
    const hint = byLabel.get(part.label) ?? byLabel.get(part.id);
    return { ...part, metadata: { ...part.metadata, proceduralPartHint: hint, isosurfaceKernel: hint ? 'robust-sparse-dual-contouring' : part.metadata.isosurfaceKernel }, children: part.children.map(attach) };
  };
  return parts.map(attach);
}

function partsFor(recipe:ReturnType<typeof resolveRecipe>){ switch(recipe.assetType){ case'humanoid':return buildHumanoidParts(recipe); case'quadruped':case'animal':case'bird':case'fish':return buildAnimalParts(recipe); case'creature':return buildAnimalParts({...recipe,assetType:'quadruped'}); case'car':case'truck':case'vehicle':return buildVehicleParts(recipe); case'bicycle':case'motorcycle':return buildBicycleParts(recipe); case'building':return buildBuildingParts(recipe); case'road':return buildRoadParts(recipe); case'bridge':return buildBridgeParts(recipe); case'terrain':return buildTerrainParts(recipe); case'tree':return buildTreeParts(recipe); case'water':return buildWaterParts(recipe); default:return buildPropParts(recipe); } }
export function buildAsset(input:Parameters<typeof resolveRecipe>[0]):ContentAsset{ const recipe=resolveRecipe(input); resetPartIds(); const id=safeSegment(String(recipe.parameters.assetId??`ce-${recipe.assetType}-${recipe.seed}`),'assetId'); const rawParts=applyProceduralPartHints(partsFor(recipe), recipe); const parts=assignProceduralUv(rawParts); const materials=assignProceduralTextureNames(defaultMaterials(recipe.assetType,recipe.parameters),id); const standard=recipe.assetType==='humanoid'?'humanoid':['quadruped','animal','creature'].includes(recipe.assetType)?'quadruped':recipe.assetType==='bird'?'bird':recipe.assetType==='fish'?'fish':['car','truck','vehicle','bicycle','motorcycle'].includes(recipe.assetType)?'vehicle-mechanical':undefined; const skeleton=standard?createSkeleton(standard,4):undefined; const animations=(skeleton? (standard==='vehicle-mechanical'?['wheel-spin','door-open','door-close','suspension-bounce']:['idle','walk','run','jump']).map(name=>({name,durationSeconds:1.2,fps:30,targetSkeleton:skeleton.id,source:'procedural' as const})):[]); const runtimeProfile=createContentEnginRuntimeProfile(recipe.profile); const performancePlan=createContentEnginPerformancePlan(runtimeProfile); const partial={id,category:categoryFor(recipe.assetType),subcategory:recipe.assetType,seed:recipe.seed,contentenginVersion:CONTENTENGIN_VERSION,recipe,parts,materials,shaders:SHADERS,skeleton,animations,collision:generateCollision(parts, recipe.assetType==='terrain'?'heightfield':'compound'),lods:generateLods(recipe.profile),runtimeProfile,performancePlan,exportProfile:recipe.profile}; const asset={...partial,validation:null as never} as ContentAsset; asset.validation=validateAsset(asset); return asset; }
