#!/usr/bin/env node

import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT = path.resolve(__dirname, '..');
const REGISTRY_PATH = path.join(ROOT, 'build-memory', 'registry.json');
const GENERATED_DIR = path.join(ROOT, 'src', 'engin', 'generated');
const GENERATED_HEADER = '// AUTO-GENERATED by scripts/wire-orphans.mjs — do not edit by hand.';

const SCAN_EXCLUDE = new Set(['.git', '.next', 'node_modules', 'dist', 'coverage']);

const APP_ROUTE_SURFACE_EXCLUDES = new Set([
  'app/error.tsx',
  'app/not-found.tsx',
  'app/loading.tsx',
  'app/global-error.tsx',
  'app/globals-enhanced.css',
]);

const SLOT_ORDER = [
  'surface',
  'route-surface',
  'engine-ruleset',
  'connector',
  'brain-node',
  'brain-doc',
  'cartridge',
  'persona',
  'migration',
  'memory',
  'dr-eams-tool',
  'hook',
  'engine-system',
  'engine-utility',
];

const GENERATED_SLOT_FILES = {
  rulesets: ['engine-ruleset'],
  surfaces: ['surface', 'route-surface'],
  connectors: ['connector'],
  cartridges: ['cartridge'],
  brain: ['brain-node', 'brain-doc'],
  personas: ['persona'],
  systems: ['engine-system', 'engine-utility'],
  hooks: ['hook'],
};

function normalizeRel(relPath) {
  return relPath.split(path.sep).join('/');
}

function removeExt(relPath) {
  const ext = path.extname(relPath);
  return ext ? relPath.slice(0, -ext.length) : relPath;
}

function inferEngine(relPath) {
  if (relPath.startsWith('engins/CodeEngin/')) return 'CodeEngin';
  if (relPath.startsWith('lib/gameengin/') || relPath.startsWith('components/gameengin/') || relPath.startsWith('components/games/')) {
    return 'GameEngin';
  }
  if (relPath === 'components/daydream/dream.LabDreamIDE.tsx') return 'LabEngin';
  if (relPath === 'components/daydream/dream.CodeDreamIDE.tsx') return 'CodeEngin';
  if (relPath.startsWith('daydreams/music/')) return 'StarmakerEngin';
  if (relPath.startsWith('components/dreamengin/')) return 'DrEamsEngin';
  if (relPath.startsWith('components/forge/') || relPath.startsWith('lib/forge-ngn/')) return 'ForgeNGN';
  return 'Universal';
}

async function walkDirectory(absDir) {
  const files = [];
  async function visit(currentDir) {
    let entries;
    try {
      entries = await fs.readdir(currentDir, { withFileTypes: true });
    } catch {
      return;
    }

    await Promise.all(entries.map(async (entry) => {
      if (entry.name.startsWith('.')) return;
      const absPath = path.join(currentDir, entry.name);
      const relPath = normalizeRel(path.relative(ROOT, absPath));

      if (entry.isDirectory()) {
        if (SCAN_EXCLUDE.has(entry.name)) return;
        await visit(absPath);
        return;
      }

      files.push(relPath);
    }));
  }

  await visit(absDir);
  return files;
}

async function collectScannedFiles() {
  const roots = [
    '.ci',
    '.github',
    'lib/Activity',
    'lib/admin',
    'lib/agentOS',
    'lib/agents',
    'agents',
    'lib/ai',
    'lib/api',
    'app',
    'assembly',
    'lib/assets',
    'lib/audio-fingerprint',
    'lib/auth',
    'lib/babylon',
    'lib/bot-detection',
    'lib/gameengin/brain',
    'lib/branding',
    'build-memory',
    'lib/gameengin/cartridges',
    'public/cartridges',
    'lib/child-safety',
    'lib/code',
    'lib/collaboration',
    'components',
    'lib/composite',
    'config',
    'lib/connectors',
    'lib/consent',
    'lib/content',
    'coresurfaces',
    'lib/daydream',
    'daydreams',
    'lib/diff',
    'dr-eams',
    'lib/dream-docs',
    'lib/dream-window',
    'lib/dreamdm',
    'dreamdmbar',
    'lib/dreamengin',
    'lib/dreamenginOS',
    'lib/dreamnav',
    'lib/dreamr',
    'lib/dreams',
    'lib/engin-runtime',
    'lib/engine',
    'engine',
    'lib/enginpipe',
    'lib/engins',
    'engins',
    'lib/event-bus',
    'lib/feature-build',
    'lib/feed',
    'lib/feeds',
    'fonts',
    'lib/forge',
    'lib/forge-ngn',
    'lib/gameengin',
    'lib/games',
    'lib/gct',
    'lib/gestures',
    'lib/god-tier',
    'lib/gsap',
    'lib/home-buttons',
    'lib/hooks',
    'hooks',
    'lib/icons',
    'lib/identity',
    'lib/intelligence',
    'lib/journey',
    'lib/marketplace',
    'lib/media',
    'supabase/migrations',
    'misc',
    'lib/music',
    'lib/navigation',
    'lib/notifications',
    'lib/observability',
    'lib/offline',
    'lib/optimizer',
    'optimizer',
    'lib/panels',
    'lib/platform',
    'lib/policy',
    'lib/reality',
    'lib/renderer',
    'lib/routing',
    'src/dream/rulesets',
    'lib/runtime',
    'lib/scene',
    'scripts',
    'lib/setup',
    'lib/sharedDream',
    'lib/shop',
    'lib/social',
    'src',
    'styles',
    'lib/supabase',
    'supabase',
    'lib/torridity',
    'types',
    'lib/ui',
    'lib/user-sim',
    'utils',
    'lib/vm',
    'lib/warp',
    'lib/web3',
    'lib/webgpu',
    'lib/widgets',
    'lib'
  ];

  const all = new Set();
  await Promise.all(roots.map(async (rootRel) => {
    const absRoot = path.join(ROOT, rootRel);
    const walked = await walkDirectory(absRoot);
    for (const file of walked) all.add(file);
  }));

  return Array.from(all).sort((a, b) => a.localeCompare(b));
}

async function detectExports(relPath) {
  const ext = path.extname(relPath);
  if (!['.ts', '.tsx', '.mts', '.cts', '.js', '.mjs', '.cjs'].includes(ext)) return [];

  try {
    const source = await fs.readFile(path.join(ROOT, relPath), 'utf8');
    const exported = new Set();

    if (/\bexport\s+default\b/m.test(source)) exported.add('default');

    const namedDecl = source.matchAll(/\bexport\s+(?:const|let|var|function|class|type|interface|enum)\s+([A-Za-z_$][\w$]*)/g);
    for (const match of namedDecl) {
      const name = match[1];
      if (name) exported.add(name);
    }

    const namedBlock = source.matchAll(/\bexport\s*\{([^}]+)\}/g);
    for (const block of namedBlock) {
      const segment = block[1];
      if (!segment) continue;
      const names = segment.split(',').map((item) => item.trim()).filter(Boolean);
      for (const name of names) {
        const asMatch = /\bas\s+([A-Za-z_$][\w$]*)$/.exec(name);
        if (asMatch?.[1]) {
          exported.add(asMatch[1]);
          continue;
        }

        const clean = name.replace(/^type\s+/, '').trim();
        if (clean) exported.add(clean);
      }
    }

    return Array.from(exported).sort((a, b) => a.localeCompare(b));
  } catch {
    return [];
  }
}

function classifySlot(relPath) {
  const isDeclarationFile = relPath.endsWith('.d.ts');
  const isTestLike = /\.((test|spec)\.(ts|tsx))$/.test(relPath);
  const isTs = relPath.endsWith('.ts') && !isDeclarationFile && !isTestLike;
  const isTsx = relPath.endsWith('.tsx') && !isTestLike;
  const isSql = relPath.endsWith('.sql');
  const isJson = relPath.endsWith('.json');
  const isMd = relPath.endsWith('.md');

  if (relPath.startsWith('components/') && (isTs || isTsx)) return 'surface';
  if (relPath.startsWith('coresurfaces/') && isTsx) return 'surface';
  if (/^daydreams\/.+\/page\.tsx$/.test(relPath)) return 'route-surface';

  if (relPath.startsWith('app/') && (isTs || isTsx) && !APP_ROUTE_SURFACE_EXCLUDES.has(relPath)) {
    return 'route-surface';
  }

  if (relPath.startsWith('engins/') && (isTs || isTsx)) return 'engine-ruleset';
  if (relPath.startsWith('src/dream/rulesets/')) return 'engine-ruleset';
  if (relPath.startsWith('lib/connectors/') && isTs) return 'connector';
  if (relPath.startsWith('lib/gameengin/brain/') && isJson) return 'brain-node';
  if (relPath.startsWith('lib/gameengin/brain/') && isMd) return 'brain-doc';
  if (relPath.startsWith('lib/gameengin/cartridges/')) return 'cartridge';
  if (/^public\/cartridges\/.+\/MANIFEST\.json$/.test(relPath)) return 'cartridge';
  if (relPath === 'agents/humanAI.persona.md' || /^agents\/humanAI\/personas\/[^/]+\.md$/.test(relPath)) return 'persona';
  if (relPath.startsWith('supabase/migrations/') && isSql) return 'migration';
  if (relPath.startsWith('build-memory/') && isJson) return 'memory';
  if (relPath.startsWith('dr-eams/')) return 'dr-eams-tool';
  if (relPath.startsWith('hooks/') && isTs) return 'hook';
  if (relPath.startsWith('lib/hooks/') && isTs) return 'hook';
  if (relPath.startsWith('lib/games/') && isTs) return 'engine-system';
  if (relPath.startsWith('lib/gameengin/') && isTs && !relPath.startsWith('lib/gameengin/brain/')) return 'engine-system';
  if (relPath.startsWith('lib/') && isTs) return 'engine-utility';

  return null;
}

function toRegistryId(relPath) {
  return removeExt(relPath);
}

function asImportLiteral(relPath) {
  const withoutSourceExtension = relPath.replace(/\.(ts|tsx|js|mjs|cjs)$/, '');
  return `@/${withoutSourceExtension}`;
}

function buildLoaderLine(entry) {
  const ext = path.extname(entry.path);
  const isDeclarationFile = entry.path.endsWith('.d.ts');
  const supportsImport = !isDeclarationFile && ['.ts', '.tsx', '.js', '.mjs', '.cjs', '.json'].includes(ext);
  if (supportsImport) {
    return `  ${JSON.stringify(entry.id)}: () => import(${JSON.stringify(asImportLiteral(entry.path))}),`;
  }

  return `  ${JSON.stringify(entry.id)}: async () => ({ default: ${JSON.stringify(entry.path)} }),`;
}

function buildGeneratedModule(name, entries) {
  const lines = [
    GENERATED_HEADER,
    '',
    `export const ${name} = {`,
    ...entries.map((entry) => buildLoaderLine(entry)),
    '};',
    '',
    `export type ${name[0].toUpperCase()}${name.slice(1)}Map = typeof ${name};`,
    '',
  ];

  return `${lines.join('\n')}`;
}

function buildGeneratedIndex() {
  return `${GENERATED_HEADER}

// Keep generated registry hydration structural so generated wiring never imports
// the core engine that dynamically loads this module.
interface EngineWithRegistry {
  registry: { hydrate: (config: Record<string, unknown>) => void };
}

import { rulesets } from './rulesets';
import { surfaces } from './surfaces';
import { connectors } from './connectors';
import { cartridges } from './cartridges';
import { brain } from './brain';
import { personas } from './personas';
import { systems } from './systems';
import { hooks } from './hooks';

export function hydrateEngineRegistry(engine: EngineWithRegistry): void {
  engine.registry.hydrate({
    rulesets,
    surfaces,
    connectors,
    cartridges,
    brain,
    personas,
    systems,
    hooks,
  });
}
`;
}

async function writeFileSafely(targetPath, content) {
  await fs.mkdir(path.dirname(targetPath), { recursive: true });
  await fs.writeFile(targetPath, content, 'utf8');
}

export async function buildRegistry(options = { write: true }) {
  const write = options.write !== false;
  const scannedFiles = await collectScannedFiles();
  const entries = [];

  for (const relPath of scannedFiles) {
    const slot = classifySlot(relPath);
    if (!slot) continue;

    const exports = await detectExports(relPath);
    entries.push({
      id: toRegistryId(relPath),
      slot,
      path: relPath,
      engine: inferEngine(relPath),
      exports,
    });
  }

  if (!entries.some((entry) => entry.path === 'build-memory/registry.json')) {
    entries.push({
      id: 'build-memory/registry',
      slot: 'memory',
      path: 'build-memory/registry.json',
      engine: 'Universal',
      exports: [],
    });
  }

  entries.sort((a, b) => a.path.localeCompare(b.path));

  const totals = Object.fromEntries(SLOT_ORDER.map((slot) => [slot, 0]));
  for (const entry of entries) {
    totals[entry.slot] = (totals[entry.slot] ?? 0) + 1;
  }

  const registry = {
    generatedAt: new Date().toISOString(),
    totals,
    entries,
  };

  if (write) {
    await writeFileSafely(REGISTRY_PATH, `${JSON.stringify(registry, null, 2)}\n`);

    await fs.mkdir(GENERATED_DIR, { recursive: true });

    const groups = Object.entries(GENERATED_SLOT_FILES).map(([name, slots]) => {
      const groupEntries = entries.filter((entry) => slots.includes(entry.slot));
      return [name, groupEntries];
    });

    for (const [name, groupEntries] of groups) {
      const content = buildGeneratedModule(name, groupEntries);
      await writeFileSafely(path.join(GENERATED_DIR, `${name}.ts`), content);
    }

    await writeFileSafely(path.join(GENERATED_DIR, 'index.ts'), buildGeneratedIndex());
  }

  return { registry, scannedFiles };
}

async function runFromCli() {
  const result = await buildRegistry({ write: true });
  const counts = result.registry.totals;
  const summary = Object.keys(counts)
    .filter((key) => (counts[key] ?? 0) > 0)
    .map((key) => `${key}:${counts[key]}`)
    .join(', ');
  console.log(`Registry generated with ${result.registry.entries.length} entries (${summary}).`);
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? '').href) {
  runFromCli().catch((error) => {
    console.error(error);
    process.exit(1);
  });
}
