import { patchBaseState, type EnginBaseState, type JsonObject } from '@/engine/engin-runtime/EnginBaseState';
import type { EnginCapability } from '@/engine/engin-runtime/EnginCapabilities';
import { getEnginCapabilityProfile } from '@/engine/engin-runtime/EnginCapabilityTargets';
import type { ConstraintResult, EnginAction, EnginConstraint, EnginRuleSetContract, EnginRuleSetManifest, EnginRuleSetParams } from '@/engine/engin-runtime/EnginRuleSetContract';
import type { ContentAsset, ContentRecipe, ExportProfile } from '@/engins/contentengin/assetTypes';
export interface ContentEnginDerivedState { lifecycle:EnginBaseState['lifecycle']; activeRecipe:ContentRecipe|null; assets:ContentAsset[]; selectedAssetId:string|null; profile:ExportProfile; photoAnalysis:JsonObject|null; lastIntent:string|null; downloads:JsonObject|null; }
export type ContentEnginAction = EnginAction<'contentengin:recipe-set',JsonObject>|EnginAction<'contentengin:asset-built',JsonObject>|EnginAction<'contentengin:asset-select',JsonObject>|EnginAction<'contentengin:profile-set',JsonObject>|EnginAction<'contentengin:photo-analyzed',JsonObject>|EnginAction<'contentengin:download-ready',JsonObject>;
const DEFAULT_DOMAIN={activeRecipe:null as ContentRecipe|null,assets:[] as ContentAsset[],selectedAssetId:null as string|null,profile:'ps3' as ExportProfile,photoAnalysis:null as JsonObject|null,lastIntent:null as string|null,downloads:null as JsonObject|null};
const constraint:EnginConstraint<ContentEnginAction>=(_s,a):ConstraintResult=>{ if(!a.type.startsWith('contentengin:')) return {valid:false,reason:'ContentEngin only accepts procedural asset intents.'}; if(a.type==='contentengin:profile-set'&&!['ps3','ps4','ps5'].includes(String(a.payload?.profile??''))) return {valid:false,reason:'Invalid export profile.'}; return {valid:true}; };
const asDomain=(d:unknown)=>d as Partial<typeof DEFAULT_DOMAIN>;
const json=(v:unknown)=>v as JsonObject;
function transform(state:EnginBaseState, action:ContentEnginAction):EnginBaseState{ const d=asDomain(state.domain); switch(action.type){ case'contentengin:recipe-set':return patchBaseState(state,{domain:json({...d,activeRecipe:action.payload?.recipe,lastIntent:action.type})}); case'contentengin:asset-built':return patchBaseState(state,{domain:json({...d,assets:[...((d.assets??[]) as ContentAsset[]),action.payload?.asset as unknown as ContentAsset],selectedAssetId:(action.payload?.asset as unknown as ContentAsset|undefined)?.id,downloads:(action.payload?.downloads as JsonObject|undefined)??d.downloads,lastIntent:action.type})}); case'contentengin:asset-select':return patchBaseState(state,{domain:json({...d,selectedAssetId:action.payload?.assetId,lastIntent:action.type})}); case'contentengin:profile-set':return patchBaseState(state,{domain:json({...d,profile:action.payload?.profile,lastIntent:action.type})}); case'contentengin:photo-analyzed':return patchBaseState(state,{domain:json({...d,photoAnalysis:action.payload?.analysis,lastIntent:action.type})}); case'contentengin:download-ready':return patchBaseState(state,{domain:json({...d,downloads:action.payload?.downloads,lastIntent:action.type})}); default:return state; } }
function deriveStateInternal(state:EnginBaseState):ContentEnginDerivedState{ const d=asDomain(state.domain); return {lifecycle:state.lifecycle,activeRecipe:d.activeRecipe??null,assets:d.assets??[],selectedAssetId:d.selectedAssetId??null,profile:d.profile??'ps3',photoAnalysis:d.photoAnalysis??null,lastIntent:d.lastIntent??null,downloads:d.downloads??null}; }
const PARAMS:EnginRuleSetParams={enginId:'create',name:'ContentEngin',layoutMode:'standard',accentColor:'#f59e0b'};
const MANIFEST:EnginRuleSetManifest<ContentEnginAction>={id:PARAMS.enginId,name:PARAMS.name,version:'2.0.0',schema:{actionTypes:['contentengin:recipe-set','contentengin:asset-built','contentengin:asset-select','contentengin:profile-set','contentengin:photo-analyzed','contentengin:download-ready'],domainVersion:2},compatibility:{minRuntimeVersion:'1.0.0',requiredFeatures:['lifecycle-hooks','manifest-schema','strict-intent-routing','sync-transport','state-snapshotting','compatibility-negotiation']}};
const REQUIRED_CAPABILITIES:ReadonlyArray<EnginCapability>=['state:read','state:write','assets:load','assets:upload','bridge:emit','bridge:listen'];
export const CONTENT_ENGIN_RULE_SET:EnginRuleSetContract<ContentEnginAction>={manifest:MANIFEST,params:PARAMS,requiredCapabilities:REQUIRED_CAPABILITIES,capabilityTargets:getEnginCapabilityProfile('create'),constraints:[constraint],transform,deriveState: deriveStateInternal as unknown as (state: EnginBaseState) => JsonObject};
