-- Auto-scaffolded migration: 20260605015234
-- Generated by: SQL Migration Guard workflow
-- Tables detected in code but not found in existing migrations:
--   widgets,content_objects,albums,album_content,collaborative_realities,reality_members,reality_state_snapshots,reality_activity_log,t,x
--
-- ⚠️  REVIEW BEFORE MERGING:
--   Add real column definitions, constraints, indexes, and RLS
--   policies that match your application's data model.

-- ── widgets ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.widgets (
  id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id   UUID        REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.widgets ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "widgets_select_own" ON public.widgets;
DROP POLICY IF EXISTS "widgets_insert_own" ON public.widgets;
DROP POLICY IF EXISTS "widgets_update_own" ON public.widgets;
DROP POLICY IF EXISTS "widgets_delete_own" ON public.widgets;

CREATE POLICY "widgets_select_own" ON public.widgets
  FOR SELECT USING (auth.uid() = owner_id);

CREATE POLICY "widgets_insert_own" ON public.widgets
  FOR INSERT WITH CHECK (auth.uid() = owner_id);

CREATE POLICY "widgets_update_own" ON public.widgets
  FOR UPDATE USING (auth.uid() = owner_id) WITH CHECK (auth.uid() = owner_id);

CREATE POLICY "widgets_delete_own" ON public.widgets
  FOR DELETE USING (auth.uid() = owner_id);

-- ── content_objects ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.content_objects (
  id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id   UUID        REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.content_objects ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "content_objects_select_own" ON public.content_objects;
DROP POLICY IF EXISTS "content_objects_insert_own" ON public.content_objects;
DROP POLICY IF EXISTS "content_objects_update_own" ON public.content_objects;
DROP POLICY IF EXISTS "content_objects_delete_own" ON public.content_objects;

CREATE POLICY "content_objects_select_own" ON public.content_objects
  FOR SELECT USING (auth.uid() = owner_id);

CREATE POLICY "content_objects_insert_own" ON public.content_objects
  FOR INSERT WITH CHECK (auth.uid() = owner_id);

CREATE POLICY "content_objects_update_own" ON public.content_objects
  FOR UPDATE USING (auth.uid() = owner_id) WITH CHECK (auth.uid() = owner_id);

CREATE POLICY "content_objects_delete_own" ON public.content_objects
  FOR DELETE USING (auth.uid() = owner_id);

-- ── albums ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.albums (
  id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id   UUID        REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.albums ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "albums_select_own" ON public.albums;
DROP POLICY IF EXISTS "albums_insert_own" ON public.albums;
DROP POLICY IF EXISTS "albums_update_own" ON public.albums;
DROP POLICY IF EXISTS "albums_delete_own" ON public.albums;

CREATE POLICY "albums_select_own" ON public.albums
  FOR SELECT USING (auth.uid() = owner_id);

CREATE POLICY "albums_insert_own" ON public.albums
  FOR INSERT WITH CHECK (auth.uid() = owner_id);

CREATE POLICY "albums_update_own" ON public.albums
  FOR UPDATE USING (auth.uid() = owner_id) WITH CHECK (auth.uid() = owner_id);

CREATE POLICY "albums_delete_own" ON public.albums
  FOR DELETE USING (auth.uid() = owner_id);

-- ── album_content ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.album_content (
  id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id   UUID        REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.album_content ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "album_content_select_own" ON public.album_content;
DROP POLICY IF EXISTS "album_content_insert_own" ON public.album_content;
DROP POLICY IF EXISTS "album_content_update_own" ON public.album_content;
DROP POLICY IF EXISTS "album_content_delete_own" ON public.album_content;

CREATE POLICY "album_content_select_own" ON public.album_content
  FOR SELECT USING (auth.uid() = owner_id);

CREATE POLICY "album_content_insert_own" ON public.album_content
  FOR INSERT WITH CHECK (auth.uid() = owner_id);

CREATE POLICY "album_content_update_own" ON public.album_content
  FOR UPDATE USING (auth.uid() = owner_id) WITH CHECK (auth.uid() = owner_id);

CREATE POLICY "album_content_delete_own" ON public.album_content
  FOR DELETE USING (auth.uid() = owner_id);

-- ── collaborative_realities ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.collaborative_realities (
  id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id   UUID        REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.collaborative_realities ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "collaborative_realities_select_own" ON public.collaborative_realities;
DROP POLICY IF EXISTS "collaborative_realities_insert_own" ON public.collaborative_realities;
DROP POLICY IF EXISTS "collaborative_realities_update_own" ON public.collaborative_realities;
DROP POLICY IF EXISTS "collaborative_realities_delete_own" ON public.collaborative_realities;

CREATE POLICY "collaborative_realities_select_own" ON public.collaborative_realities
  FOR SELECT USING (auth.uid() = owner_id);

CREATE POLICY "collaborative_realities_insert_own" ON public.collaborative_realities
  FOR INSERT WITH CHECK (auth.uid() = owner_id);

CREATE POLICY "collaborative_realities_update_own" ON public.collaborative_realities
  FOR UPDATE USING (auth.uid() = owner_id) WITH CHECK (auth.uid() = owner_id);

CREATE POLICY "collaborative_realities_delete_own" ON public.collaborative_realities
  FOR DELETE USING (auth.uid() = owner_id);

-- ── reality_members ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.reality_members (
  id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id   UUID        REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.reality_members ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "reality_members_select_own" ON public.reality_members;
DROP POLICY IF EXISTS "reality_members_insert_own" ON public.reality_members;
DROP POLICY IF EXISTS "reality_members_update_own" ON public.reality_members;
DROP POLICY IF EXISTS "reality_members_delete_own" ON public.reality_members;

CREATE POLICY "reality_members_select_own" ON public.reality_members
  FOR SELECT USING (auth.uid() = owner_id);

CREATE POLICY "reality_members_insert_own" ON public.reality_members
  FOR INSERT WITH CHECK (auth.uid() = owner_id);

CREATE POLICY "reality_members_update_own" ON public.reality_members
  FOR UPDATE USING (auth.uid() = owner_id) WITH CHECK (auth.uid() = owner_id);

CREATE POLICY "reality_members_delete_own" ON public.reality_members
  FOR DELETE USING (auth.uid() = owner_id);

-- ── reality_state_snapshots ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.reality_state_snapshots (
  id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id   UUID        REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.reality_state_snapshots ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "reality_state_snapshots_select_own" ON public.reality_state_snapshots;
DROP POLICY IF EXISTS "reality_state_snapshots_insert_own" ON public.reality_state_snapshots;
DROP POLICY IF EXISTS "reality_state_snapshots_update_own" ON public.reality_state_snapshots;
DROP POLICY IF EXISTS "reality_state_snapshots_delete_own" ON public.reality_state_snapshots;

CREATE POLICY "reality_state_snapshots_select_own" ON public.reality_state_snapshots
  FOR SELECT USING (auth.uid() = owner_id);

CREATE POLICY "reality_state_snapshots_insert_own" ON public.reality_state_snapshots
  FOR INSERT WITH CHECK (auth.uid() = owner_id);

CREATE POLICY "reality_state_snapshots_update_own" ON public.reality_state_snapshots
  FOR UPDATE USING (auth.uid() = owner_id) WITH CHECK (auth.uid() = owner_id);

CREATE POLICY "reality_state_snapshots_delete_own" ON public.reality_state_snapshots
  FOR DELETE USING (auth.uid() = owner_id);

-- ── reality_activity_log ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.reality_activity_log (
  id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id   UUID        REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.reality_activity_log ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "reality_activity_log_select_own" ON public.reality_activity_log;
DROP POLICY IF EXISTS "reality_activity_log_insert_own" ON public.reality_activity_log;
DROP POLICY IF EXISTS "reality_activity_log_update_own" ON public.reality_activity_log;
DROP POLICY IF EXISTS "reality_activity_log_delete_own" ON public.reality_activity_log;

CREATE POLICY "reality_activity_log_select_own" ON public.reality_activity_log
  FOR SELECT USING (auth.uid() = owner_id);

CREATE POLICY "reality_activity_log_insert_own" ON public.reality_activity_log
  FOR INSERT WITH CHECK (auth.uid() = owner_id);

CREATE POLICY "reality_activity_log_update_own" ON public.reality_activity_log
  FOR UPDATE USING (auth.uid() = owner_id) WITH CHECK (auth.uid() = owner_id);

CREATE POLICY "reality_activity_log_delete_own" ON public.reality_activity_log
  FOR DELETE USING (auth.uid() = owner_id);

-- ── t ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.t (
  id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id   UUID        REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.t ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "t_select_own" ON public.t;
DROP POLICY IF EXISTS "t_insert_own" ON public.t;
DROP POLICY IF EXISTS "t_update_own" ON public.t;
DROP POLICY IF EXISTS "t_delete_own" ON public.t;

CREATE POLICY "t_select_own" ON public.t
  FOR SELECT USING (auth.uid() = owner_id);

CREATE POLICY "t_insert_own" ON public.t
  FOR INSERT WITH CHECK (auth.uid() = owner_id);

CREATE POLICY "t_update_own" ON public.t
  FOR UPDATE USING (auth.uid() = owner_id) WITH CHECK (auth.uid() = owner_id);

CREATE POLICY "t_delete_own" ON public.t
  FOR DELETE USING (auth.uid() = owner_id);

-- ── x ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.x (
  id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id   UUID        REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.x ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "x_select_own" ON public.x;
DROP POLICY IF EXISTS "x_insert_own" ON public.x;
DROP POLICY IF EXISTS "x_update_own" ON public.x;
DROP POLICY IF EXISTS "x_delete_own" ON public.x;

CREATE POLICY "x_select_own" ON public.x
  FOR SELECT USING (auth.uid() = owner_id);

CREATE POLICY "x_insert_own" ON public.x
  FOR INSERT WITH CHECK (auth.uid() = owner_id);

CREATE POLICY "x_update_own" ON public.x
  FOR UPDATE USING (auth.uid() = owner_id) WITH CHECK (auth.uid() = owner_id);

CREATE POLICY "x_delete_own" ON public.x
  FOR DELETE USING (auth.uid() = owner_id);

