name: Sync Types

on:
  workflow_dispatch:

jobs:
  update-types:
    runs-on: ubuntu-latest
    env:
      SUPABASE_PROJECT_ID: "suaiqcynxospjijzdudc"
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Generate types
        run: |
          supabase gen types typescript --project-id $SUPABASE_PROJECT_ID --schema public > types/supabase.ts

      - name: Commit types
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add types/supabase.ts
          git commit -m "chore: sync schema types [skip ci]" || echo "No changes"
          git push
